apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: che
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 1000
      containers:
        - image: yzzhangllm/chemx:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            runAsNonRoot: true
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1000"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1h"
