apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: isosh
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - name: fl
          image: yzzhangllm/flaskshimg:latest
          ports:
          - containerPort: 12346

        - name : sh
          image: yzzhangllm/isoshimage:latest
          resources:
            requests:
              cpu: "20000m"  # 请求最小250 millicpu
            limits:
              cpu: "20000m"  # 限制最大500 millicpu

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: vm
                    operator: In
                    values:
                      - MT  # 假设VMA是目标节点的标签
