
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: mlstrigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: mlsmsg
  subscriber:
    ref: 
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: isomls
  delivery:
    retry: 0
