
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: mlttrigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: mltmsg
  subscriber:
    ref: 
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: isomlt
  delivery:
    retry: 0
