
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: restrigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: resmsg
  subscriber:
    ref: 
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: isores
  delivery:
    retry: 0
