
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: mattrigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: matmsg
  subscriber:
    ref: 
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: isomat
  delivery:
    retry: 0
