
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: pyaetrigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: pyaemsg
  subscriber:
    ref: 
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: isopyae
  delivery:
    retry: 0
