apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fakeivk
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - name : ivk
          image: yzzhangllm/fakeivkimg:latest

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: vm
                    operator: In
                    values:
                      - MT  # 假设VMA是目标节点的标签
