apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: omp
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 1000
      containers:
        - image: yzzhangllm/ompmx:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            runAsNonRoot: true
          resources:
            requests:
              cpu: 1000m
              memory: 3Gi
            limits:
              cpu: 24
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1000"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1h"
