apiVersion: v1
kind: Pod
metadata:
  name: curlpod
spec:
  containers:
  - name: curlcontainer
    image: yzzhangllm/curlpod:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: vm
                operator: In
                values:
                  - Cu